[package]
name = "lesson1"
version = "0.1.0"
authors = ["Eric Klein <eric.klein@workday.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"
regex = "1.5.4"
itertools = "0.8.0"